FROM golang:1.23 AS builder

WORKDIR /app

COPY . .

RUN go mod tidy && CGO_ENABLED=0 GOOS=linux go build -o auth_service cmd/auth/main.go 

FROM alpine:latest
COPY --from=builder /app/auth_service /auth_service
RUN chmod +x /auth_service
EXPOSE 8081
CMD [ "/auth_service" ]