FROM golang:1.23 AS builder

WORKDIR /app

COPY . .

RUN go mod tidy && CGO_ENABLED=0 GOOS=linux go build -o currrency_service cmd/currency/main.go 

FROM alpine:latest
COPY --from=builder /app/currrency_service /currrency_service
RUN chmod +x /currrency_service
EXPOSE 8082
CMD [ "/currrency_service" ]